openapi: 3.0.3
info:
  title: Example components schemas from business_objects.py
components:
  schemas:
    Address:
      description: Represents a physical address, where mail could be sent.
      properties:
        building_address:
          anyOf:
          - type: string
          - type: 'null'
          default: null
          description: The "building address" (an apartment number, suite, etc.) portion
            of the address that the instance represents
          example: null
          title: Building Address
        city:
          description: The city portion of the address that the instance represents
          example: Springfield
          title: City
          type: string
        country:
          anyOf:
          - type: string
          - type: 'null'
          default: null
          description: The country portion of the address that the instance represents.
            Typically omitted, indicating that the address is "local" to the country
            of origin.
          example: null
          title: Country
        postal_code:
          description: The postal code portion (a ZIP Code in the US, for example)
            of the address that the instance represents
          example: '12345'
          title: Postal Code
          type: string
        region:
          description: The region portion (a state in the US, or a province in Canada,
            for example) of the address that the instance represents
          example: Some Place
          title: Region
          type: string
        street_address:
          description: The street address portion of the address that the instance
            represents. May also contain a post office box
          example: 1234 Main Street
          title: Street Address
          type: string
      required:
      - street_address
      - city
      - region
      - postal_code
      title: Address
      type: object
    BaseArtisan:
      description: Provides baseline functionality, interface requirements, and type
        identity for objects that can represent an Artisan in the system.
      properties:
        address:
          $ref: '#/components/schemas/Address'
          description: The mailing address for the Artisan that the instance represents
          title: Mailing Address
        email_address:
          description: The email address for the Artisan that the instance represents
          example: jsmith@gmail.com
          pattern: ^[a-zA-Z0-9\._%+\-]+@[a-zA-Z0-9\.\-]+\.[a-zA-Z]{2,}$
          title: Email Address
          type: string
        family_name:
          description: The family name of the artisan that the instance represents
          example: Smith
          minLength: 2
          title: Family Name
          type: string
        given_name:
          description: The given name of the artisan that the instance represents
          example: John
          minLength: 2
          title: Given Name
          type: string
        honorific:
          anyOf:
          - maxLength: 7
            minLength: 2
            type: string
          - type: 'null'
          default: null
          description: The honorific of the Artisan that the instance represents
          example: null
          title: Honorific
        phone:
          description: The phone number address for the Artisan that the instance
            represents
          example: 303-555-1212
          pattern: ^(\+\d{1,2}\s)?\(?\d{3}\)?[\s.-]\d{3}[\s.-]\d{4}$
          title: Phone Number
          type: string
        suffix:
          anyOf:
          - maxLength: 7
            minLength: 2
            type: string
          - type: 'null'
          default: null
          description: The name suffix of the Artisan that the instance represents
          example: null
          title: Suffix
      required:
      - given_name
      - family_name
      - address
      - phone
      - email_address
      title: BaseArtisan
      type: object
